"""Wire models, one module per schema family (``docs/api/``)."""

from __future__ import annotations

from open_mammotion.models.action import ActionResult, WorkAction
from open_mammotion.models.common import (
    SUCCESS_CODES,
    Envelope,
    IntBool,
    JsonObject,
    JsonValue,
    TolerantIntEnum,
    TolerantStrEnum,
    WireModel,
    describe_decode_error,
    int_bool,
    utc_from_ms,
    utc_from_s,
)
from open_mammotion.models.device import DeviceDetail, DeviceInfo, DeviceStatus, Network, NetworkType
from open_mammotion.models.fault import Attachment, Fault, FaultLevel, FaultPage, FaultQuery, NotificationPriority
from open_mammotion.models.local_network import (
    DispatchStatus,
    LocalNetworkConfig,
    LocalNetworkDevice,
    LocalNetworkQueryRequest,
    LocalNetworkSaveRequest,
    WsTicket,
    WsTicketRequest,
)
from open_mammotion.models.task import WorkTask
from open_mammotion.models.work_params import ChannelMode, JobContent, ObstacleMode, PathOrder, TowardMode, WorkParams
from open_mammotion.models.work_report import (
    ReportJobContent,
    WorkEvent,
    WorkProcessEvent,
    WorkReport,
    WorkReportDetail,
    WorkReportPage,
    WorkReportQuery,
    WorkReportSummary,
    WorkResult,
    WorkType,
)

__all__ = [
    "SUCCESS_CODES",
    "ActionResult",
    "Attachment",
    "ChannelMode",
    "DeviceDetail",
    "DeviceInfo",
    "DeviceStatus",
    "DispatchStatus",
    "Envelope",
    "Fault",
    "FaultLevel",
    "FaultPage",
    "FaultQuery",
    "IntBool",
    "JobContent",
    "JsonObject",
    "JsonValue",
    "LocalNetworkConfig",
    "LocalNetworkDevice",
    "LocalNetworkQueryRequest",
    "LocalNetworkSaveRequest",
    "Network",
    "NetworkType",
    "NotificationPriority",
    "ObstacleMode",
    "PathOrder",
    "ReportJobContent",
    "TolerantIntEnum",
    "TolerantStrEnum",
    "TowardMode",
    "WireModel",
    "WorkAction",
    "WorkEvent",
    "WorkParams",
    "WorkProcessEvent",
    "WorkReport",
    "WorkReportDetail",
    "WorkReportPage",
    "WorkReportQuery",
    "WorkReportSummary",
    "WorkResult",
    "WorkTask",
    "WorkType",
    "WsTicket",
    "WsTicketRequest",
    "describe_decode_error",
    "int_bool",
    "utc_from_ms",
    "utc_from_s",
]
